### ISSUE TITLE
Error on opening MISE11-VILA's scene2 results in partial import

### ISSUE THREAD

**Issue by TheNameAsaIsNotAvailable** [hostar/YAMSE#2]
Hi there, I've been using the software more recently but today got:
> Destination array is not long enough to copy all the items in the collection. Check array index and length. (Parameter 'value')

Owing to partial import(?), it was missing the last few thousand lines of (I think) a script data portion _(see pic)_. Mission is vanilla, so just thought I'd flag it.

![bug](https://user-images.githubusercontent.com/111624709/185732511-5456db57-f98e-476e-8da5-916718837044.png)

Aside from that, looking forward to seeing where this goes! Really like the inbuilt hex capability.

**Comment by hostar** [comment]
Hello, thanks for the report, I am glad you find this tool useful.
The problem was in the special object "@zidle", fixed version here: https://github.com/hostar/YAMSE/releases/tag/v0.2

I temporarily abandoned the project in favor of other work, but before I did, I started working on editing of header (View distance, Near, Far etc.). So this version contains the fix for Villa mission and supports editing of the file header.
